# Generated by Django 2.2.3 on 2019-10-20 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apache1', models.FileField(null=True, upload_to='')),
                ('envvars', models.FileField(null=True, upload_to='')),
                ('security', models.FileField(null=True, upload_to='')),
            ],
        ),
    ]
